// src/components/PayslipGenerator.jsx
import React, { useEffect, useState } from "react";

/**
 * Simple Payslip Generator for managers.
 * - fetches employees
 * - fetches attendance for a month/year and auto-calculates working days for selected employee
 * - supports selecting a template and editing salary/deductions
 * - preview + print
 *
 * NOTE: adapt CSS classes to your app or convert to styled-components.
 */

const TEMPLATES = [
  { id: "basic", name: "Basic - Clean", header: "Company Name", footer: "Thank you" },
  { id: "compact", name: "Compact - Two column", header: "Company Name", footer: "Generated by Attendance" },
];

const PRESENT_FULL = ["PRESENT FULL DAY", "PRESENT"];
const HALF_DAY_STATUSES = ["PRESENT HALF DAY", "Half Day - Fun Thursday", "Half Day - Development"];

const statusToValue = (status) => {
  if (!status) return 0;
  if (PRESENT_FULL.includes(status)) return 1;
  if (HALF_DAY_STATUSES.includes(status)) return 0.5;
  // treat COMPOFF as worked? you can decide; default 0
  return 0;
};

export default function PayslipGenerator() {
  const [employees, setEmployees] = useState([]);
  const [loadingEmployees, setLoadingEmployees] = useState(false);
  const [selectedEmployeeId, setSelectedEmployeeId] = useState("");
  const [month, setMonth] = useState(String(new Date().getMonth() + 1).padStart(2, "0"));
  const [year, setYear] = useState(String(new Date().getFullYear()));
  const [attendance, setAttendance] = useState([]); // fetched attendance for the month
  const [workingDays, setWorkingDays] = useState(0);

  const [templateId, setTemplateId] = useState("basic");

  // payslip editable fields
  const [basicSalary, setBasicSalary] = useState(30000);
  const [hra, setHra] = useState(6000);
  const [otherAllowances, setOtherAllowances] = useState(2000);
  const [deductions, setDeductions] = useState(1500);
  const [notes, setNotes] = useState("");

  // token helper (adjust to your auth)
  const getAuthHeaders = () => {
    const token = localStorage.getItem("token") || "";
    return {
      Authorization: token ? `Bearer ${token}` : "",
      "Content-Type": "application/json",
    };
  };

  useEffect(() => {
    // load employees
    const loadEmployees = async () => {
      setLoadingEmployees(true);
      try {
        const res = await fetch("/api/employees", {
          headers: getAuthHeaders(),
        });
        if (!res.ok) throw new Error("Failed to load employees");
        const data = await res.json();
        setEmployees(data);
        if (data.length && !selectedEmployeeId) {
          setSelectedEmployeeId(data[0]._id || data[0].id);
        }
      } catch (err) {
        console.error("Employees load error", err);
      } finally {
        setLoadingEmployees(false);
      }
    };

    loadEmployees();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // load attendance for the month/year whenever month/year changes
  useEffect(() => {
    const loadAttendance = async () => {
      try {
        setAttendance([]);
        // manager endpoint: GET /api/attendance?month=MM&year=YYYY
        const res = await fetch(`/api/attendance?month=${String(Number(month))}&year=${year}`, {
          headers: getAuthHeaders(),
        });
        if (!res.ok) throw new Error("Failed to load attendance");
        const data = await res.json(); // array, populated with user for manager endpoint
        // keep in state
        setAttendance(data);
      } catch (err) {
        console.error("Attendance load error", err);
      }
    };

    loadAttendance();
  }, [month, year]);

  // compute workingDays when attendance or selected employee changes
  useEffect(() => {
    if (!selectedEmployeeId || !attendance || attendance.length === 0) {
      setWorkingDays(0);
      return;
    }

    // attendance returned by /api/attendance is an array of records (populated with user)
    const filtered = attendance.filter((r) => {
      const uid = r.user?._id || r.user;
      return String(uid) === String(selectedEmployeeId);
    });

    let sum = 0;
    for (const r of filtered) {
      sum += statusToValue(r.status);
    }

    setWorkingDays(sum);
  }, [attendance, selectedEmployeeId]);

  const handleGenerateClientPDF = () => {
    // We show a preview and call browser print — simplest approach.
    // You might want to generate a server-side PDF instead (see notes below).
    setTimeout(() => {
      // opens print dialog with current page content — we'll focus on preview element via CSS print rules
      window.print();
    }, 200);
  };

  const handleServerGenerate = async () => {
    // optional: post to backend to generate PDF on server and return file
    try {
      const payload = {
        employeeId: selectedEmployeeId,
        month,
        year,
        templateId,
        fields: {
          basicSalary,
          hra,
          otherAllowances,
          deductions,
          notes,
          workingDays,
        },
      };

      const res = await fetch("/api/payslips/generate", {
        method: "POST",
        headers: getAuthHeaders(),
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.message || "Server generate failed");
      }

      // if server returns PDF blob:
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `payslip-${selectedEmployeeId}-${month}-${year}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Server generate error", err);
      alert("Server generation failed: " + err.message);
    }
  };

  const employee = employees.find((e) => String(e._id || e.id) === String(selectedEmployeeId));

  const gross = Number(basicSalary) + Number(hra) + Number(otherAllowances);
  const net = gross - Number(deductions);

  return (
    <div className="payslip-generator">
      <h2>Payslip Generator (Manager)</h2>

      <div className="controls">
        <label>
          Employee
          <select value={selectedEmployeeId} onChange={(e) => setSelectedEmployeeId(e.target.value)}>
            {loadingEmployees ? <option>Loading...</option> : employees.map((emp) => (
              <option key={emp._id || emp.id} value={emp._id || emp.id}>
                {emp.fullName || emp.email}
              </option>
            ))}
          </select>
        </label>

        <label>
          Month
          <input type="number" min="1" max="12" value={Number(month)} onChange={(e) => setMonth(String(e.target.value).padStart(2, "0"))} />
        </label>

        <label>
          Year
          <input type="number" min="2000" max="2100" value={year} onChange={(e) => setYear(e.target.value)} />
        </label>

        <label>
          Template
          <select value={templateId} onChange={(e) => setTemplateId(e.target.value)}>
            {TEMPLATES.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
          </select>
        </label>
      </div>

      <div className="salary-form">
        <div>
          <label>Working days (auto)</label>
          <input type="number" value={workingDays} readOnly />
        </div>

        <div>
          <label>Basic Salary</label>
          <input type="number" value={basicSalary} onChange={(e) => setBasicSalary(Number(e.target.value))} />
        </div>

        <div>
          <label>HRA</label>
          <input type="number" value={hra} onChange={(e) => setHra(Number(e.target.value))} />
        </div>

        <div>
          <label>Other Allowances</label>
          <input type="number" value={otherAllowances} onChange={(e) => setOtherAllowances(Number(e.target.value))} />
        </div>

        <div>
          <label>Deductions</label>
          <input type="number" value={deductions} onChange={(e) => setDeductions(Number(e.target.value))} />
        </div>

        <div style={{ gridColumn: "1 / -1" }}>
          <label>Notes</label>
          <textarea value={notes} onChange={(e) => setNotes(e.target.value)} />
        </div>
      </div>

      <div className="actions">
        <button onClick={handleGenerateClientPDF}>Preview & Print (client)</button>
        <button onClick={handleServerGenerate}>Generate on Server (PDF)</button>
      </div>

      {/* -------------------- Preview -------------------- */}
      <div className="payslip-preview" id="payslip-preview" style={{ marginTop: 24, border: "1px solid #ddd", padding: 16 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div>
            <h3>{TEMPLATES.find(t => t.id === templateId)?.header}</h3>
            <div style={{ fontSize: 14 }}>{TEMPLATES.find(t => t.id === templateId)?.name}</div>
          </div>
          <div>
            <strong>Payslip</strong>
            <div>{month}/{year}</div>
          </div>
        </div>

        <hr />

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
          <div>
            <div><strong>Employee:</strong> {employee?.fullName || employee?.email || "—"}</div>
            <div><strong>Email:</strong> {employee?.email || "—"}</div>
          </div>
          <div>
            <div><strong>Working days:</strong> {workingDays}</div>
            <div><strong>Employee ID:</strong> {employee?.employeeId || "-"}</div>
          </div>
        </div>

        <div style={{ marginTop: 12 }}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                <th style={{ textAlign: "left", borderBottom: "1px solid #ccc" }}>Earnings</th>
                <th style={{ textAlign: "right", borderBottom: "1px solid #ccc" }}>Amount</th>
                <th style={{ textAlign: "left", borderBottom: "1px solid #ccc" }}>Deductions</th>
                <th style={{ textAlign: "right", borderBottom: "1px solid #ccc" }}>Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Basic</td>
                <td style={{ textAlign: "right" }}>{basicSalary.toFixed(2)}</td>
                <td>Deductions</td>
                <td style={{ textAlign: "right" }}>{deductions.toFixed(2)}</td>
              </tr>
              <tr>
                <td>HRA</td>
                <td style={{ textAlign: "right" }}>{hra.toFixed(2)}</td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td>Other Allowances</td>
                <td style={{ textAlign: "right" }}>{otherAllowances.toFixed(2)}</td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
            <tfoot>
              <tr style={{ borderTop: "1px solid #ccc" }}>
                <td><strong>Gross</strong></td>
                <td style={{ textAlign: "right" }}><strong>{gross.toFixed(2)}</strong></td>
                <td><strong>Net Pay</strong></td>
                <td style={{ textAlign: "right" }}><strong>{net.toFixed(2)}</strong></td>
              </tr>
            </tfoot>
          </table>
        </div>

        <div style={{ marginTop: 12 }}>
          <strong>Notes:</strong>
          <div>{notes || "-"}</div>
        </div>

        <div style={{ marginTop: 20, textAlign: "right" }}>
          <div>{TEMPLATES.find(t => t.id === templateId)?.footer}</div>
        </div>
      </div>
    </div>
  );
}
